service: api-mutant

provider:
  name: aws
  runtime: java8
  region: us-east-1
  timeout: 30
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"
  
package:
  artifact: target/api-mutant-1.0.0-SNAPSHOT.jar
  
functions:
  verificar:
    handler: br.com.mutant.handler.MutantHandler
    events:
      - http:
          path: /mutant
          method: post
          cors: true
          
  estatistica:
    handler: br.com.mutant.handler.StatHandler
    events:
      - http:
          path: /stats
          method: get
          cors: true

resources:
  Resources:
    DynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: DNA
        AttributeDefinitions:
          - AttributeName: Id
            AttributeType: S
          - AttributeName: Mutant
            AttributeType: N
        KeySchema:
          - AttributeName: Id
            KeyType: HASH
          - AttributeName: Mutant
            KeyType: RANGE
        GlobalSecondaryIndexes: 
        - IndexName: "Mutant-index"
          KeySchema: 
          - AttributeName: "Mutant"
            KeyType: "HASH"
          Projection: 
            ProjectionType: "ALL"
          ProvisionedThroughput: 
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1
        ProvisionedThroughput: 
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1